name: myenv

channels:
 - defaults
 - anaconda
 - nvidia
 - conda-forge
 - pytorch

dependencies:
  - pandas
  - numpy
  - plotly
  - matplotlib
  - seaborn
  - azure-storage-blob
  - anaconda
  - transformers
  - pip
  - pip:
      - opencv-python
      - opencv-python-headless
      - opencv-contrib-python
      - jupyterlab-lsp
      - python-lsp-server
      - jupyter
      - notebook
      - python-dotenv
      - tqdm
      # - torch
      # - torchvision
      # - torchaudio
      # - chardet
      # - torchserve
      # - sagemaker
      # - boto3